services:
  gophish:
    build: .
    container_name: gophish-container
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - gophish_db:/opt/gophish/gophish.db

  caddy:
    image: caddy:latest
    container_name: gophish-caddy-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from ${DOMAIN} --to gophish:8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  gophish_db:
  caddy_data:
  caddy_config:
