name: Docker - Build and Deploy (Gophish)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'are you ready to deploy?'
        required: true
        default: 'yes'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. AWS 인증 (Secrets 사용)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      # 2. Docker 이미지 빌드 및 푸시
      - name: Build and push image
        env:
          ECR_REGISTRY: public.ecr.aws/${{ vars.ECR_PUBLIC_REGISTRY_ID }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --push \
            --provenance=false \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            -t $ECR_REGISTRY/yourssu/$PROJECT_NAME:$IMAGE_TAG \
            -t $ECR_REGISTRY/yourssu/$PROJECT_NAME:latest \
            .

      # 3. 서버 배포
      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_STG_HOST }}
          
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          SERVER_PORT: ${{ vars.SERVER_PORT }}
          REGISTRY_ID: ${{ vars.ECR_PUBLIC_REGISTRY_ID }}
        run: |
          mkdir -p ~/.ssh
          LATEST_TAG=$(aws ecr-public describe-images \
            --repository-name yourssu/$PROJECT_NAME \
            --region us-east-1 \
            --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' \
            --output text)
          
          echo "Found latest tag in ECR: $LATEST_TAG"

          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

          # 서버에 디렉토리 생성
          ssh -i key.pem ubuntu@$HOST "mkdir -p /home/ubuntu/${PROJECT_NAME}"
          
          # .env 파일 생성
          echo "SERVER_PORT=$SERVER_PORT" > .env
          echo "PROJECT_NAME=$PROJECT_NAME" >> .env
          echo "ECR_REGISTRY=public.ecr.aws/$REGISTRY_ID" >> .env
          echo "IMAGE_TAG=$LATEST_TAG" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          
          # 파일 전송
          scp -i key.pem .env ubuntu@$HOST:/home/ubuntu/${PROJECT_NAME}/.env
          scp -i key.pem docker-compose.yml ubuntu@$HOST:/home/ubuntu/${PROJECT_NAME}/docker-compose.yml
          scp -i key.pem config.json ubuntu@$HOST:/home/ubuntu/${PROJECT_NAME}/config.json
          
          # 배포 명령 실행 (docker-compose 사용)
          ssh -i key.pem ubuntu@$HOST "mkdir -p /home/ubuntu/${PROJECT_NAME} && cd /home/ubuntu/${PROJECT_NAME} && \
            docker compose pull && \
            docker compose up -d"
